version: "3.8"
services:
  gotenberg:
    image: gotenberg/gotenberg:7.7.0
    ports:
      - "3009:3000"
    command:
      - "gotenberg"
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--pdfengines-engines=pdftk"
      - "--uno-listener-restart-threshold=0"
