services:
  zap:
    image: zaproxy/zap-stable
    container_name: zaproxy
    ports:
      - "8080:8080"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
      - tail -f dev/null
