version: '3.1'
services:

  redis:
    image: 'redis:7.0'
    networks:
      - hmpps_int
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps_int
    container_name: localstack-resettlement-passport-ui
    ports:
      - "4565:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"

networks:
  hmpps_int:
