services:

  redis:
    image: 'redis:7.0'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-resettlement-passport-ui
    ports:
      - "4565:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  gotenberg:
    image: gotenberg/gotenberg:7.7.0
    networks:
      - hmpps
    ports:
      - "3005:3005"
    command:
      - "gotenberg"
      - "--api-port=3005"
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--pdfengines-engines=pdftk"
      - "--uno-listener-restart-threshold=0" #disables uno listener
    restart: on-failure
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3005/health' ]

networks:
  hmpps:
