import { stubFor } from '../../wiremock'
import { responseHeaders } from '../../headers'

const getAccommodationSupportNeedsSummaryNoSupportNeeds = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION/summary',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        prisonerNeeds: [],
      },
    },
    scenarioName: 'john-smith-accommodation-get-no-support-needs-summary',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsUpdatesNoSupportNeeds = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION/updates?page=0&size=10&sort=createdDate,DESC&filterByPrisonerSupportNeedId=',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        updates: [],
      },
    },
    scenarioName: 'john-smith-accommodation-get-no-support-needs-updates',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsNoSupportNeeds = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        supportNeeds: [
          {
            id: 1,
            title: 'End a tenancy',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 2,
            title: 'Maintain a tenancy while in prison',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 3,
            title: 'Mortgage support while in prison',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 4,
            title:
              'Home adaptations to stay in current accommodation (changes to make it safer and easier to move around and do everyday tasks)',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 5,
            title: 'Arrange storage for personal possessions while in prison',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 6,
            title: 'Other',
            category: 'Accommodation before custody',
            allowUserDesc: true,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 7,
            title: 'No accommodation before custody support needs identified',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: false,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 8,
            title: 'Help to find accommodation',
            category: 'Moving to new accommodation',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 9,
            title:
              'Home adaptations needed for new accommodation (changes to make it safer and easier to move around and do everyday tasks)',
            category: 'Moving to new accommodation',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 10,
            title: 'Other',
            category: 'Moving to new accommodation',
            allowUserDesc: true,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 11,
            title: 'No new accommodation support needs identified',
            category: 'Moving to new accommodation',
            allowUserDesc: false,
            isUpdatable: false,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 12,
            title: 'Set up payment for rent arrears',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 13,
            title: 'Ensure accommodation related debt or arrears do not build up',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 14,
            title: 'Other',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: true,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 15,
            title: 'No accommodation related debt and arrears support needs identified',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: false,
            isUpdatable: false,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
        ],
      },
    },
    scenarioName: 'john-smith-accommodation-get-no-support-needs',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsSummaryWithSupportNeeds = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION/summary',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        prisonerNeeds: [
          {
            id: 286,
            title: 'End a tenancy',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            status: 'NOT_STARTED',
            numberOfUpdates: 1,
            lastUpdated: '2025-05-02',
          },
          {
            id: 288,
            title: 'Custom accommodation support need',
            isPrisonResponsible: false,
            isProbationResponsible: true,
            status: 'IN_PROGRESS',
            numberOfUpdates: 1,
            lastUpdated: '2025-05-02',
          },
          {
            id: 289,
            title: 'Maintain a tenancy while in prison',
            isPrisonResponsible: false,
            isProbationResponsible: true,
            status: 'NOT_STARTED',
            numberOfUpdates: 1,
            lastUpdated: '2025-05-02',
          },
        ],
      },
    },
    scenarioName: 'john-smith-accommodation-get-support-needs-summary',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsUpdatesWithSupportNeeds = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION/updates?page=0&size=10&sort=createdDate,DESC&filterByPrisonerSupportNeedId=',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        updates: [
          {
            id: 616,
            prisonerNeedId: 293,
            title: 'End a tenancy',
            status: 'IN_PROGRESS',
            isPrisonResponsible: true,
            isProbationResponsible: true,
            text: null,
            createdBy: 'Mary Ford',
            createdAt: '2025-05-06T13:18:40.676304',
          },
          {
            id: 615,
            prisonerNeedId: 293,
            title: 'End a tenancy',
            status: 'IN_PROGRESS',
            isPrisonResponsible: true,
            isProbationResponsible: true,
            text: 'Update',
            createdBy: 'Mary Ford',
            createdAt: '2025-05-06T13:08:56.507828',
          },
          {
            id: 604,
            prisonerNeedId: 295,
            title: 'Mortgage support while in prison',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: '',
            createdBy: 'Chris Waugh',
            createdAt: '2025-05-02T12:40:05.906286',
          },
          {
            id: 603,
            prisonerNeedId: 294,
            title: 'Maintain a tenancy while in prison',
            status: 'IN_PROGRESS',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: '',
            createdBy: 'Chris Waugh',
            createdAt: '2025-05-02T12:33:43.831832',
          },
          {
            id: 602,
            prisonerNeedId: 293,
            title: 'End a tenancy',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: '',
            createdBy: 'Chris Waugh',
            createdAt: '2025-05-02T12:32:39.249894',
          },
          {
            id: 601,
            prisonerNeedId: 283,
            title: 'Mortgage support while in prison',
            status: null,
            isPrisonResponsible: false,
            isProbationResponsible: false,
            text: 'Support need removed because of profile reset\n\nReason for reset: ZK Test',
            createdBy: 'Zahid Khan',
            createdAt: '2025-05-02T11:59:52.711587',
          },
          {
            id: 600,
            prisonerNeedId: 285,
            title: 'Ensure accommodation related debt or arrears do not build up',
            status: null,
            isPrisonResponsible: false,
            isProbationResponsible: false,
            text: 'Support need removed because of profile reset\n\nReason for reset: ZK Test',
            createdBy: 'Zahid Khan',
            createdAt: '2025-05-02T11:59:52.711544',
          },
          {
            id: 596,
            prisonerNeedId: 285,
            title: 'Ensure accommodation related debt or arrears do not build up',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: '',
            createdBy: 'Zahid Khan',
            createdAt: '2025-04-30T23:05:55.751225',
          },
          {
            id: 595,
            prisonerNeedId: 283,
            title: 'Mortgage support while in prison',
            status: 'IN_PROGRESS',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: 'testing',
            createdBy: 'Zahid Khan',
            createdAt: '2025-04-30T23:05:55.735107',
          },
          {
            id: 594,
            prisonerNeedId: 277,
            title: 'Support with staying in accommodation upon release',
            status: null,
            isPrisonResponsible: false,
            isProbationResponsible: false,
            text: 'Support need removed because of profile reset\n\nReason for reset: Test',
            createdBy: 'Zahid Khan',
            createdAt: '2025-04-30T23:04:03.517328',
          },
        ],
        allPrisonerNeeds: [
          {
            id: 290,
            title: 'No accommodation before custody support needs identified',
          },
          {
            id: 291,
            title: 'No new accommodation support needs identified',
          },
          {
            id: 292,
            title: 'No accommodation related debt and arrears support needs identified',
          },
          {
            id: 293,
            title: 'End a tenancy',
          },
          {
            id: 294,
            title: 'Maintain a tenancy while in prison',
          },
          {
            id: 295,
            title: 'Mortgage support while in prison',
          },
        ],
        size: 10,
        page: 0,
        sortName: 'createdDate,DESC',
        totalElements: 418,
        last: false,
      },
    },
    scenarioName: 'john-smith-accommodation-get-support-needs-updates',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsUpdatesWithSupportNeedsASC = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION/updates?page=0&size=10&sort=createdDate,ASC&filterByPrisonerSupportNeedId=',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        updates: [
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: In progress. testing new nomsid',
            createdBy: 'Akiva Moshecorn',
            createdAt: '2023-11-16T15:23:21',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: In progress. In progress - accommodation code 2 ',
            createdBy: 'Usharani Arugonda',
            createdAt: '2023-11-17T15:13:44',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: Not started. ',
            createdBy: 'Iain Harkis',
            createdAt: '2023-11-22T08:43:22',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: In progress. Referral started to get some accommodation',
            createdBy: 'Iain Harkis',
            createdAt: '2023-11-22T11:33:55',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: Support not required. no need was identified',
            createdBy: 'Usharani Arugonda',
            createdAt: '2023-11-23T14:50:03',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: Support declined. a need was identified but support was declined',
            createdBy: 'Usharani Arugonda',
            createdAt: '2023-11-23T14:51:29',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: Support not required. no need was identified',
            createdBy: 'Usharani Arugonda',
            createdAt: '2023-11-23T14:51:41',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: In progress. ',
            createdBy: 'Usharani Arugonda',
            createdAt: '2023-11-23T15:12:48',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: Support not required. ',
            createdBy: 'James Boobier',
            createdAt: '2023-11-23T15:29:05',
          },
          {
            id: 0,
            prisonerNeedId: null,
            title: 'Accommodation (case note)',
            status: null,
            isPrisonResponsible: null,
            isProbationResponsible: null,
            text: 'Resettlement status set to: In progress. ',
            createdBy: 'James Boobier',
            createdAt: '2023-11-23T15:37:12',
          },
        ],
        allPrisonerNeeds: [
          {
            id: 290,
            title: 'No accommodation before custody support needs identified',
          },
          {
            id: 291,
            title: 'No new accommodation support needs identified',
          },
          {
            id: 292,
            title: 'No accommodation related debt and arrears support needs identified',
          },
          {
            id: 293,
            title: 'End a tenancy',
          },
          {
            id: 294,
            title: 'Maintain a tenancy while in prison',
          },
          {
            id: 295,
            title: 'Mortgage support while in prison',
          },
        ],
        size: 10,
        page: 0,
        sortName: 'createdDate,ASC',
        totalElements: 418,
        last: false,
      },
    },
    scenarioName: 'john-smith-accommodation-get-support-needs-updates-sorted-asc',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsUpdatesWithSupportNeedsPage2 = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION/updates?page=1&size=10&sort=createdDate,DESC&filterByPrisonerSupportNeedId=',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        updates: [
          {
            id: 593,
            prisonerNeedId: 273,
            title: 'End a tenancy',
            status: null,
            isPrisonResponsible: false,
            isProbationResponsible: false,
            text: 'Support need removed because of profile reset\n\nReason for reset: Test',
            createdBy: 'Zahid Khan',
            createdAt: '2025-04-30T23:04:03.517327',
          },
          {
            id: 589,
            prisonerNeedId: 282,
            title: 'Mortgage support while in prison',
            status: null,
            isPrisonResponsible: false,
            isProbationResponsible: false,
            text: 'Support need removed because of profile reset\n\nReason for reset: Test',
            createdBy: 'Zahid Khan',
            createdAt: '2025-04-30T23:04:03.517319',
          },
          {
            id: 588,
            prisonerNeedId: 276,
            title: 'Maintain a tenancy while in prison',
            status: null,
            isPrisonResponsible: false,
            isProbationResponsible: false,
            text: 'Support need removed because of profile reset\n\nReason for reset: Test',
            createdBy: 'Zahid Khan',
            createdAt: '2025-04-30T23:04:03.517223',
          },
          {
            id: 587,
            prisonerNeedId: 273,
            title: 'End a tenancy',
            status: 'MET',
            isPrisonResponsible: true,
            isProbationResponsible: true,
            text: null,
            createdBy: 'Chris Waugh',
            createdAt: '2025-04-30T16:33:24.285788',
          },
          {
            id: 586,
            prisonerNeedId: 273,
            title: 'End a tenancy',
            status: 'MET',
            isPrisonResponsible: false,
            isProbationResponsible: true,
            text: null,
            createdBy: 'Mary Ford',
            createdAt: '2025-04-25T11:24:48.588651',
          },
          {
            id: 585,
            prisonerNeedId: 273,
            title: 'End a tenancy',
            status: 'MET',
            isPrisonResponsible: false,
            isProbationResponsible: true,
            text: null,
            createdBy: 'Mary Ford',
            createdAt: '2025-04-25T11:24:44.805063',
          },
          {
            id: 584,
            prisonerNeedId: 282,
            title: 'Mortgage support while in prison',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: 'Test',
            createdBy: 'James Boobier',
            createdAt: '2025-04-25T11:24:05.143572',
          },
          {
            id: 583,
            prisonerNeedId: 273,
            title: 'End a tenancy',
            status: 'MET',
            isPrisonResponsible: false,
            isProbationResponsible: true,
            text: null,
            createdBy: 'Natasha Zeki',
            createdAt: '2025-04-24T16:44:18.008599',
          },
          {
            id: 577,
            prisonerNeedId: 277,
            title: 'Support with staying in accommodation upon release',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: true,
            text: '',
            createdBy: 'Kate Weir',
            createdAt: '2025-04-23T13:48:38.662761',
          },
          {
            id: 576,
            prisonerNeedId: 276,
            title: 'Maintain a tenancy while in prison',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: '',
            createdBy: 'James Boobier',
            createdAt: '2025-04-23T10:26:35.132877',
          },
        ],
        allPrisonerNeeds: [
          {
            id: 290,
            title: 'No accommodation before custody support needs identified',
          },
          {
            id: 291,
            title: 'No new accommodation support needs identified',
          },
          {
            id: 292,
            title: 'No accommodation related debt and arrears support needs identified',
          },
          {
            id: 293,
            title: 'End a tenancy',
          },
          {
            id: 294,
            title: 'Maintain a tenancy while in prison',
          },
          {
            id: 295,
            title: 'Mortgage support while in prison',
          },
        ],
        size: 10,
        page: 1,
        sortName: 'createdDate,DESC',
        totalElements: 418,
        last: false,
      },
    },
    scenarioName: 'john-smith-accommodation-get-support-needs-updates-page-2',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedsWithSupportNeeds = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/needs/ACCOMMODATION',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        supportNeeds: [
          {
            id: 3,
            title: 'Mortgage support while in prison',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 4,
            title:
              'Home adaptations to stay in current accommodation (changes to make it safer and easier to move around and do everyday tasks)',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 5,
            title: 'Arrange storage for personal possessions while in prison',
            category: 'Accommodation before custody',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 6,
            title: 'Other',
            category: 'Accommodation before custody',
            allowUserDesc: true,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 8,
            title: 'Help to find accommodation',
            category: 'Moving to new accommodation',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 9,
            title:
              'Home adaptations needed for new accommodation (changes to make it safer and easier to move around and do everyday tasks)',
            category: 'Moving to new accommodation',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 10,
            title: 'Other',
            category: 'Moving to new accommodation',
            allowUserDesc: true,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 11,
            title: 'No new accommodation support needs identified',
            category: 'Moving to new accommodation',
            allowUserDesc: false,
            isUpdatable: false,
            isPreSelected: true,
            existingPrisonerSupportNeedId: 287,
          },
          {
            id: 12,
            title: 'Set up payment for rent arrears',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 13,
            title: 'Ensure accommodation related debt or arrears do not build up',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: false,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
          {
            id: 14,
            title: 'Other',
            category: 'Accommodation related debt and arrears',
            allowUserDesc: true,
            isUpdatable: true,
            isPreSelected: false,
            existingPrisonerSupportNeedId: null,
          },
        ],
      },
    },
    scenarioName: 'john-smith-accommodation-get-support-needs',
    requiredScenarioState: 'Started',
  })
}

const getAccommodationSupportNeedEndATenancy = () => {
  return stubFor({
    request: {
      url: '/rpApi/resettlement-passport/prisoner/A8731DY/prisoner-need/286',
      method: 'GET',
    },
    response: {
      status: 200,
      headers: responseHeaders,
      jsonBody: {
        title: 'End a tenancy',
        isPrisonResponsible: true,
        isProbationResponsible: false,
        status: 'NOT_STARTED',
        previousUpdates: [
          {
            id: 597,
            prisonerNeedId: 286,
            title: 'End a tenancy',
            status: 'NOT_STARTED',
            isPrisonResponsible: true,
            isProbationResponsible: false,
            text: '',
            createdBy: 'Mary Ford',
            createdAt: '2025-05-02T11:23:45.080951',
          },
        ],
      },
    },
    scenarioName: 'john-smith-accommodation-get-support-need-end-a-tenancy',
    requiredScenarioState: 'Started',
  })
}

export const johnSmithGetAccommodationSupportNeedsNoSupportNeeds = () => [
  getAccommodationSupportNeedsSummaryNoSupportNeeds(),
  getAccommodationSupportNeedsUpdatesNoSupportNeeds(),
  getAccommodationSupportNeedsNoSupportNeeds(),
]

export const johnSmithGetAccommodationSupportNeedsWithSupportNeeds = () => [
  getAccommodationSupportNeedsSummaryWithSupportNeeds(),
  getAccommodationSupportNeedsUpdatesWithSupportNeeds(),
  getAccommodationSupportNeedsUpdatesWithSupportNeedsASC(),
  getAccommodationSupportNeedsUpdatesWithSupportNeedsPage2(),
  getAccommodationSupportNeedsWithSupportNeeds(),
  getAccommodationSupportNeedEndATenancy(),
]
