{
 "title": "HMPPS Resettlement Passport",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, namespace)"
    }
   },
   {
    "name": "authType",
    "label": "Auth Type",
    "query": {
     "query": "label_values(user_activity_count, auth_type)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(user_activity_count, path)"
    }
   },
   {
    "name": "caseload",
    "label": "Caseload",
    "query": {
     "query": "label_values(user_activity_count, caseload)"
    }
   },
   {
    "name": "prison",
    "label": "Prison",
    "query": {
     "query": "label_values(total_prisoners_count,prison)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prisoners Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(total_prisoners_count{namespace=~\"$namespace\", prison=\"$prison\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(total_prisoners_12Weeks_count{namespace=~\"$namespace\", prison=\"$prison\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(total_prisoners_24Weeks_count{namespace=\"$namespace\", prison=\"$prison\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(total_prisoners_AllTime_count{namespace=\"$namespace\", prison=\"$prison\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "API Pod Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=~'$namespace', service='hmpps-resettlement-passport-api'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "UI Pod Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=~'$namespace', service='hmpps-resettlement-passport-ui'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "User Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Page views",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "round (sum by (path, auth_type) (increase(user_activity_count{namespace=~'$namespace', auth_type=~'$authType', path=~'$path', caseload=~'$caseload'}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approx. total page hits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(user_activity_count{namespace=~'$namespace', auth_type=~'$authType', path=~'$path', caseload=~'$caseload'}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (auth_type) (increase(user_activity_count{namespace=~'$namespace'}[$__range]))) != 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Paths",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (path) (increase(user_activity_count{namespace=~'$namespace'}[$__range]))) != 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Caseload",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (caseload) (increase(user_activity_count{namespace=~'$namespace'}[$__range]))) != 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}