---
# Per environment values which override defaults in hmpps-resettlement-passport-ui/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: hmpps-resettlement-passport-dev-irsa

  ingress:
    host: resettlement-passport-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://resettlement-passport-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    RESETTLEMENT_PASSPORT_API_URL: "https://resettlement-passport-api-dev.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-dev.prison.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: "DEV"
    SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk/feedback-and-support"
    GOTENBERG_API_URL: "http://hmpps-resettlement-passport-ui-gotenberg"


  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons
      - circleci

generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod

deploy_grafana_dashboards: true


