# Per environment values which override defaults in hmpps-resettlement-passport-ui/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: hmpps-resettlement-passport-preprod-irsa

  ingress:
    host: resettlement-passport-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://resettlement-passport-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    RESETTLEMENT_PASSPORT_API_URL: "https://resettlement-passport-api-preprod.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: "PRE-PRODUCTION"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk/feedback-and-support"
    GOTENBERG_API_URL: "http://hmpps-resettlement-passport-ui-gotenberg"

generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod
