name: Build and run zap test
on:
  workflow_call:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
permissions:
  contents: read
jobs:
  zap-test:
    runs-on: [self-hosted, Linux, X64, hmpps-github-actions-runner]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: Install Playwright
        run: npm run setup -g playwright && npx playwright install
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: download the artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: npm_build_artifacts
      - name: Setup ZAP
        uses: ./.github/actions/setup-zap
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Run zap tests
        run: |
          export ST_USERNAME=${{ secrets.E2E_DEV_USERNAME }}
          export ST_PASSWORD=${{ secrets.E2E_DEV_PASSWORD }}
          export ST_PROXY_URL="http://localhost:8080"
          export ST_API_KEY=''
          export ST_ENV_NAME='dev'
          mkdir -p test_results
          pip install -r ./security_test/requirements.txt
          playwright install chromium
          owasp-zap -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true &
          sleep 60  # Wait for ZAP to start
          python3 ./security_test/test_security.py
      - name: upload the artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: npm_zap_test_artifacts
          path: test_results
      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2
        with:
          artifact: npm_zap_test_artifacts
          name: Test Report
          path: 'jest/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
