name: Build and run pt browser smoke test
on:
  workflow_call:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
permissions:
  contents: read
jobs:
  pt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm_build_artifacts
      - uses: grafana/setup-k6-action@v1
        with:
          browser: true
      - name: set up environment variables
        run: |
            export PT_USERNAME=${E2E_DEV_USERNAME}
            export PT_PASSWORD=${E2E_DEV_PASSWORD}
            export EXECUTION_TYPE=smoke
            export PROCESS=dev
      - uses: grafana/run-k6-action@v1
        env:
          EXECUTION_TYPE: smoke
          PROCESS: dev
        with:
          path: |
            pt_tests/tests/run.js
#          flags: |
#            --no-setup
#      - name: run pt browser smoke test
#        run: |
#            export PT_USERNAME=${E2E_DEV_USERNAME}
#            export PT_PASSWORD=${E2E_DEV_PASSWORD}
#            k6 run pt_tests/tests/run.js --no-setup
#        env:
#          execution_type: smoke
#          process: dev
      - name: upload the artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: pt_browser_smoke_test_artifacts
          path: test_results
      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@v2
        with:
          artifact: pt_browser_smoke_test_artifacts
          name: Test Report
          path: 'jest/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
